Company.create(:id => 4170, :name => "Арсеньевская авиационная корпорация Прогрессим.Н.И.Сазыкина", :slug => "aakp")
Company.create(:id => 4171, :name => "Абаканвагонмаш", :slug => "abvm")
Company.create(:id => 4172, :name => "Агрегат", :slug => "agrt")
Company.create(:id => 4173, :name => "ИЛ", :slug => "akil")
Company.create(:id => 4174, :name => "Судостроительная фирма АЛМАЗ", :slug => "almz")
Company.create(:id => 4175, :name => "Алтайвагон", :slug => "alvg")
Company.create(:id => 4176, :name => "Анжеромаш", :slug => "ange")
Company.create(:id => 4177, :name => "Автоприцеп - КАМАЗ", :slug => "apkm")
Company.create(:id => 4178, :name => "Арзамасский приборостроительный завод", :slug => "apsz")
Company.create(:id => 4179, :name => "Машиностроительный завод Арсенал", :slug => "arse")
Company.create(:id => 4180, :name => "АВТОВАЗ", :slug => "avaz")
Company.create(:id => 4181, :name => "Автодизель", :slug => "avdz")
Company.create(:id => 4182, :name => "Авиаагрегат", :slug => "avgt")
Company.create(:id => 4183, :name => "Балтийский завод", :slug => "balz")
Company.create(:id => 4184, :name => "Белебеевский завод Автонормаль", :slug => "belz")
Company.create(:id => 4185, :name => "Брянский арсенал", :slug => "brar")
Company.create(:id => 4186, :name => "Барнаултрансмаш", :slug => "btsm")
Company.create(:id => 4187, :name => "Буммаш", :slug => "bumm")
Company.create(:id => 4188, :name => "Чебоксарский агрегатный завод", :slug => "chaz")
Company.create(:id => 4189, :name => "Чепецкий механический завод", :slug => "cherp")
Company.create(:id => 4190, :name => "Копейский машзавод", :slug => "comz")
Company.create(:id => 4191, :name => "Завод Дагдизель", :slug => "dadz")
Company.create(:id => 4192, :name => "Электроагрегат", :slug => "elag")
Company.create(:id => 4193, :name => "Элара", :slug => "elar")
Company.create(:id => 4194, :name => "ЭЛАКС", :slug => "elax")
Company.create(:id => 4195, :name => "ЭЛСИБ", :slug => "elib")
Company.create(:id => 4196, :name => "Элеконд", :slug => "elkd")
Company.create(:id => 4197, :name => "Электровыпрямитель", :slug => "elvp")
Company.create(:id => 4198, :name => "Фазотрон-НИИР", :slug => "fztr")
Company.create(:id => 4199, :name => "ГАЗ", :slug => "gaza")
Company.create(:id => 4200, :name => "Агат", :slug => "gyaa")
Company.create(:id => 4201, :name => "Холдинговая компания Электрозавод", :slug => "hkez")
Company.create(:id => 4202, :name => "Ижевский машзавод", :slug => "igma")
Company.create(:id => 4203, :name => "НПО Искра", :slug => "iskr")
Company.create(:id => 4204, :name => "Ижорские заводы", :slug => "izhzp")
Company.create(:id => 4205, :name => "ИЖНЕФТЕМАШ", :slug => "iznm")
Company.create(:id => 4206, :name => "Калужский двигатель", :slug => "kadv")
Company.create(:id => 4207, :name => "Ковровский электромеханический завод", :slug => "kemz")
Company.create(:id => 4208, :name => "Казанский вертолетный завод", :slug => "khel")
Company.create(:id => 4209, :name => "Кировский завод", :slug => "kirz")
Company.create(:id => 4210, :name => "КАМАЗ", :slug => "kmaz")
Company.create(:id => 4211, :name => "Казанский оптико-механический завод", :slug => "komz")
Company.create(:id => 4212, :name => "Калугапутьмаш", :slug => "kpmg")
Company.create(:id => 4213, :name => "КМПО", :slug => "kpmo")
Company.create(:id => 4214, :name => "Криогенмаш", :slug => "krgm")
Company.create(:id => 4215, :name => "ТКЗ Красный Котельщик", :slug => "krko")
Company.create(:id => 4216, :name => "Завод Красное Сормово", :slug => "ksmv")
Company.create(:id => 4217, :name => "Калужский турбинный завод", :slug => "ktyr")
Company.create(:id => 4218, :name => "Корвет", :slug => "kvet")
Company.create(:id => 4219, :name => "Ковровский механический завод", :slug => "kvmz")
Company.create(:id => 4220, :name => "Калужский завод автомобильного электрооборудования", :slug => "kzae")
Company.create(:id => 4221, :name => "Красноярский завод холодильников \"Бирюса", :slug => "kzhb")
Company.create(:id => 4222, :name => "Красногорский завод им. С.А. Зверева", :slug => "kziz")
Company.create(:id => 4223, :name => "Казанькомпрессормаш", :slug => "kzkm")
Company.create(:id => 4224, :name => "Кировский завод Маяк", :slug => "kzmk")
Company.create(:id => 4225, :name => "Электромашиностроительный завод ЛЕПСЕ", :slug => "leps")
Company.create(:id => 4226, :name => "ЛОМО", :slug => "lomo")
Company.create(:id => 4227, :name => "ЛесснерЪ", :slug => "lsnr")
Company.create(:id => 4228, :name => "Лебедянский завод строительно-отделочных машин", :slug => "lzsm")
Company.create(:id => 4229, :name => "Магнитогорский метизно-калибровочный завод", :slug => "mmmz")
Company.create(:id => 4230, :name => "Московский машиностроительный завод Вперед", :slug => "mmzv")
Company.create(:id => 4231, :name => "Мотовилихинские заводы", :slug => "motz")
Company.create(:id => 4232, :name => "Московский подшипник", :slug => "mpod")
Company.create(:id => 4233, :name => "Машиностроительное производственное объединение имени И. Румянцева", :slug => "mpor")
Company.create(:id => 4234, :name => "Муромский стрелочный завод", :slug => "mstz")
Company.create(:id => 4235, :name => "Муромтепловоз", :slug => "murt")
Company.create(:id => 4236, :name => "Московский завод электроизмерительных приборов", :slug => "mzep")
Company.create(:id => 4237, :name => "Машиностроительный завод имени М.И. Калинина", :slug => "mzik")
Company.create(:id => 4238, :name => "Московский завод счетно-аналитических машин имени В.Д.Калмыкова", :slug => "mzsm")
Company.create(:id => 4239, :name => "Нижегородский авиастроительный завод Сокол", :slug => "naso")
Company.create(:id => 4240, :name => "Нижнеангарсктрансстрой", :slug => "nats")
Company.create(:id => 4241, :name => "НПО НАУКА", :slug => "nauk")
Company.create(:id => 4242, :name => "Нефтекамский автозавод", :slug => "nfaz")
Company.create(:id => 4243, :name => "Гидромаш", :slug => "ngrm")
Company.create(:id => 4244, :name => "Нижегородский машиностроительный завод", :slug => "nmsz")
Company.create(:id => 4245, :name => "Научно-производственное объединение Физика", :slug => "npof")
Company.create(:id => 4246, :name => "ОМЗ", :slug => "omzz")
Company.create(:id => 4247, :name => "Павловский автобус", :slug => "paza")
Company.create(:id => 4248, :name => "Пермские моторы", :slug => "pmot")
Company.create(:id => 4249, :name => "Промтрактор", :slug => "prta")
Company.create(:id => 4250, :name => "Ростсельмаш", :slug => "rtlm")
Company.create(:id => 4251, :name => "Сатурн", :slug => "strn")
Company.create(:id => 4252, :name => "СОЛЛЕРС", :slug => "svav")
Company.create(:id => 4253, :name => "УАЗ", :slug => "uaza")
Company.create(:id => 4254, :name => "Выборгский судостроительный завод", :slug => "vssz")
Company.create(:id => 4255, :name => "Московское машиностроительное предприятие имени В.В. Чернышева", :slug => "mpch")
Company.create(:id => 4256, :name => "Кировский машзавод 1 Мая", :slug => "kmzm")
Company.create(:id => 4257, :name => "Объединенная авиастроительная корпорация", :slug => "unac")
Company.create(:id => 4258, :name => "TESLA MOTORS", :slug => "tsla")
Company.create(:id => 4259, :name => "ЭЛТЕЗА", :slug => "elteza")
Company.create(:id => 4260, :name => "АККОНД", :slug => "acnd")
Company.create(:id => 4261, :name => "Агрофирма Мценская", :slug => "afmc")
Company.create(:id => 4262, :name => "ПАВА", :slug => "akha")
Company.create(:id => 4263, :name => "Агропромышленный комплекс Максимовский", :slug => "akmx")
Company.create(:id => 4264, :name => "Химико-фармацевтический комбинат Акрихин", :slug => "akph")
Company.create(:id => 4265, :name => "Аптечная сеть 36,6", :slug => "aptk")
Company.create(:id => 4266, :name => "Аванта", :slug => "avnt")
Company.create(:id => 4267, :name => "Бавария", :slug => "bava")
Company.create(:id => 4268, :name => "Букет Чувашии", :slug => "bchv")
Company.create(:id => 4269, :name => "Биосинтез", :slug => "bios")
Company.create(:id => 4270, :name => "Брянский молочный комбинат", :slug => "bmko")
Company.create(:id => 4271, :name => "Череповецкий Мясокомбинат", :slug => "chrm")
Company.create(:id => 4272, :name => "Камчатрыбпром", :slug => "cmrp")
Company.create(:id => 4273, :name => "Дальхимфарм", :slug => "dahf")
Company.create(:id => 4274, :name => "Дятьково-ДОЗ", :slug => "ddoz")
Company.create(:id => 4275, :name => "ДИКСИ Групп", :slug => "dixy")
Company.create(:id => 4276, :name => "ДОК Красный Октябрь", :slug => "dkko")
Company.create(:id => 4277, :name => "Фармстандарт-Томскхимфарм", :slug => "fast")
Company.create(:id => 4278, :name => "Фармацевтическая фабрика Санкт-Петербурга", :slug => "ffsp")
Company.create(:id => 4279, :name => "Группа Черкизово", :slug => "gche")
Company.create(:id => 4280, :name => "Группа Разгуляй", :slug => "graz")
Company.create(:id => 4281, :name => "ТД ГУМ", :slug => "gumm")
Company.create(:id => 4282, :name => "Гулькевичский КХП", :slug => "gykp")
Company.create(:id => 4283, :name => "Хлебный дом", :slug => "hleb")
Company.create(:id => 4284, :name => "Илецксоль", :slug => "ilso")
Company.create(:id => 4285, :name => "Ювелиры Урала", :slug => "jewu")
Company.create(:id => 4286, :name => "КБК Черемушки", :slug => "kbkc")
Company.create(:id => 4287, :name => "Искож", :slug => "kcik")
Company.create(:id => 4288, :name => "Концерн Калина", :slug => "klna")
Company.create(:id => 4289, :name => "Кондитерская фабрика", :slug => "konf")
Company.create(:id => 4290, :name => "Консервщик", :slug => "kons")
Company.create(:id => 4291, :name => "КОПЕЙКА", :slug => "kopk")
Company.create(:id => 4292, :name => "Кореновсксахар", :slug => "kors")
Company.create(:id => 4293, :name => "Красный Октябрь", :slug => "krot")
Company.create(:id => 4294, :name => "Красный Восток Агро", :slug => "krva")
Company.create(:id => 4295, :name => "Синтез, г.Курган", :slug => "ksin")
Company.create(:id => 4296, :name => "ЮНИМИЛК", :slug => "kunm")
Company.create(:id => 4297, :name => "Казанский жировой комбинат", :slug => "kzhk")
Company.create(:id => 4298, :name => "Ламзурь", :slug => "lamz")
Company.create(:id => 4299, :name => "Магнит", :slug => "mgnt")
Company.create(:id => 4300, :name => "Молочный комбинат Пензенский", :slug => "mkpz")
Company.create(:id => 4301, :name => "Мебельная компания Шатура", :slug => "mksh")
Company.create(:id => 4302, :name => "Мясоптицекомбинат Пензенский", :slug => "mpkp")
Company.create(:id => 4303, :name => "Мясокомбинат Ульяновский", :slug => "muln")
Company.create(:id => 4304, :name => "М.Видео", :slug => "mvid")
Company.create(:id => 4305, :name => "Московский вертолетный завод им. М.Л. Миля", :slug => "mvzm")
Company.create(:id => 4306, :name => "Находкинская база активного морского рыболовства", :slug => "nbam")
Company.create(:id => 4307, :name => "Невская Косметика", :slug => "ncos")
Company.create(:id => 4308, :name => "Новосибхимфарм", :slug => "nhfm")
Company.create(:id => 4309, :name => "Научно-производственная фирма Пигмент", :slug => "pgmn")
Company.create(:id => 4310, :name => "Фармстандарт", :slug => "phst")
Company.create(:id => 4311, :name => "Балтика", :slug => "pkba")
Company.create(:id => 4312, :name => "Седьмой Континент", :slug => "scon")
Company.create(:id => 4313, :name => "Синергия", :slug => "syng")
Company.create(:id => 4314, :name => "Тамбовское Спиртоводочное Предприятие Талвис", :slug => "tlvs")
Company.create(:id => 4315, :name => "ВЕРОФАРМ", :slug => "vrph")
Company.create(:id => 4316, :name => "Вимм-Билль-Данн Продукты Питания", :slug => "wbdf")
Company.create(:id => 4317, :name => "Алтайсельэлектросетьстрой", :slug => "aess")
Company.create(:id => 4318, :name => "Архэнергосбыт", :slug => "arsb")
Company.create(:id => 4319, :name => "Астраханская энергосбытовая компания", :slug => "assb")
Company.create(:id => 4320, :name => "Башкирэнерго", :slug => "begy")
Company.create(:id => 4321, :name => "Корпоративные сервисные системы", :slug => "benr")
Company.create(:id => 4322, :name => "Богучанская ГЭС", :slug => "bges")
Company.create(:id => 4323, :name => "Белгородская сбытовая компания", :slug => "blsb")
Company.create(:id => 4324, :name => "Брянская сбытовая компания", :slug => "bnsb")
Company.create(:id => 4325, :name => "Бурятэнергосбыт", :slug => "busb")
Company.create(:id => 4326, :name => "Е4 - Центрэнергомонтаж", :slug => "cems")
Company.create(:id => 4327, :name => "ЧЭСК", :slug => "chsb")
Company.create(:id => 4328, :name => "Челябэнергосбыт", :slug => "clsb")
Company.create(:id => 4329, :name => "Дагестанская энергосбытовая компания", :slug => "dasb")
Company.create(:id => 4330, :name => "Дальэнергомонтаж", :slug => "denm")
Company.create(:id => 4331, :name => "ДЭК", :slug => "dvec")
Company.create(:id => 4332, :name => "Электроцентромонтаж", :slug => "elcm")
Company.create(:id => 4333, :name => "Энергоспецмонтаж", :slug => "espm")
Company.create(:id => 4334, :name => "ФСК ЕЭС", :slug => "fees")
Company.create(:id => 4335, :name => "ГТ-ТЭЦ Энерго", :slug => "gten")
Company.create(:id => 4336, :name => "РусГидро", :slug => "hydr")
Company.create(:id => 4337, :name => "Интер РАО ЕЭС", :slug => "irao")
Company.create(:id => 4338, :name => "Иркутскэнерго", :slug => "irgz")
Company.create(:id => 4339, :name => "Иркут", :slug => "irkt")
Company.create(:id => 4340, :name => "Ивэнергосбыт", :slug => "ivsb")
Company.create(:id => 4341, :name => "Кубанская генерирующая компания", :slug => "kbgr")
Company.create(:id => 4342, :name => "Кубаньэнергосбыт", :slug => "kbsb")
Company.create(:id => 4343, :name => "Камчатскэнерго", :slug => "kche")
Company.create(:id => 4344, :name => "Коми энергосбытовая компания", :slug => "kesk")
Company.create(:id => 4345, :name => "Кировэнергосбыт", :slug => "kisb")
Company.create(:id => 4346, :name => "Калужская сбытовая компания", :slug => "klsb")
Company.create(:id => 4347, :name => "Кубанские магистральные сети", :slug => "knms")
Company.create(:id => 4348, :name => "Колэнергосбыт", :slug => "kosb")
Company.create(:id => 4349, :name => "Курганэнерго", :slug => "krge")
Company.create(:id => 4350, :name => "Красноярскэнергосбыт", :slug => "krsb")
Company.create(:id => 4351, :name => "Костромская сбытовая компания", :slug => "ktsb")
Company.create(:id => 4352, :name => "Кубаньэнерго", :slug => "kube")
Company.create(:id => 4353, :name => "Курскэнергосбыт", :slug => "kusb")
Company.create(:id => 4354, :name => "Кузбасская энергетическая сбытовая компания", :slug => "kzsb")
Company.create(:id => 4355, :name => "Липецкая энергосбытовая компания", :slug => "lpsb")
Company.create(:id => 4356, :name => "Ленэнерго", :slug => "lsng")
Company.create(:id => 4357, :name => "Магаданэнерго", :slug => "mage")
Company.create(:id => 4358, :name => "Мариэнергосбыт", :slug => "misb")
Company.create(:id => 4359, :name => "Московская объединенная энергетическая компания", :slug => "moek")
Company.create(:id => 4360, :name => "МРСК Центра", :slug => "mrkc")
Company.create(:id => 4361, :name => "Холдинг МРСК", :slug => "mrkh")
Company.create(:id => 4362, :name => "МРСК Северного Кавказа", :slug => "mrkk")
Company.create(:id => 4363, :name => "МРСК Центра и Приволжья", :slug => "mrkp")
Company.create(:id => 4364, :name => "МРСК Сибири", :slug => "mrks")
Company.create(:id => 4365, :name => "МРСК Урала", :slug => "mrku")
Company.create(:id => 4366, :name => "МРСК Волги", :slug => "mrkv")
Company.create(:id => 4367, :name => "МРСК Юга", :slug => "mrky")
Company.create(:id => 4368, :name => "МРСК Северо-Запада", :slug => "mrkz")
Company.create(:id => 4369, :name => "Мордовская энергосбытовая компания", :slug => "mrsb")
Company.create(:id => 4370, :name => "Мосэнерго", :slug => "msng")
Company.create(:id => 4371, :name => "Мостеплосетьэнергоремонт", :slug => "mter")
Company.create(:id => 4372, :name => "Мурманская ТЭЦ", :slug => "mugs")
Company.create(:id => 4373, :name => "Ноябрьскэлектросетьстрой", :slug => "ness")
Company.create(:id => 4374, :name => "Новгородская энергосбытовая компания", :slug => "ngsb")
Company.create(:id => 4375, :name => "Нижегородская сбытовая компания", :slug => "nnsb")
Company.create(:id => 4376, :name => "Новосибирскэнерго", :slug => "nvng")
Company.create(:id => 4377, :name => "ОГК-1", :slug => "ogka")
Company.create(:id => 4378, :name => "ОГК-2", :slug => "ogkb")
Company.create(:id => 4379, :name => "ОГК-3", :slug => "ogkc")
Company.create(:id => 4380, :name => "ОГК-4", :slug => "ogkd")
Company.create(:id => 4381, :name => "Энел ОГК-5", :slug => "ogke")
Company.create(:id => 4382, :name => "ОГК-6", :slug => "ogkf")
Company.create(:id => 4383, :name => "Омскэнергосбыт", :slug => "omsb")
Company.create(:id => 4384, :name => "Орелэнергосбыт", :slug => "orsb")
Company.create(:id => 4385, :name => "Петербургская сбытовая компания", :slug => "pbsb")
Company.create(:id => 4386, :name => "Пермэнергосбыт", :slug => "pmsb")
Company.create(:id => 4387, :name => "Пензаэнергосбыт", :slug => "pzsb")
Company.create(:id => 4388, :name => "Энергосбыт Ростовэнерго", :slug => "rtsb")
Company.create(:id => 4389, :name => "Рязанская энергетическая сбытовая компания", :slug => "rzsb")
Company.create(:id => 4390, :name => "Самараэнерго", :slug => "sago")
Company.create(:id => 4391, :name => "Саратовэнерго", :slug => "sare")
Company.create(:id => 4392, :name => "Смоленскэнергосбыт", :slug => "smsb")
Company.create(:id => 4393, :name => "Свердловэнергосбыт", :slug => "svsb")
Company.create(:id => 4394, :name => "Тамбовская энергосбытовая компания", :slug => "tasb")
Company.create(:id => 4395, :name => "ТГК-11 Холдинг", :slug => "tghk")
Company.create(:id => 4396, :name => "ТГК-1", :slug => "tgka")
Company.create(:id => 4397, :name => "ТГК-2", :slug => "tgkb")
Company.create(:id => 4398, :name => "Квадра", :slug => "tgkd")
Company.create(:id => 4399, :name => "ТГК-5", :slug => "tgke")
Company.create(:id => 4400, :name => "ТГК-6", :slug => "tgkf")
Company.create(:id => 4401, :name => "Волжская ТГК (ТГК-7)", :slug => "tgkg")
Company.create(:id => 4402, :name => "ТГК-9", :slug => "tgki")
Company.create(:id => 4403, :name => "Фортум", :slug => "tgkj")
Company.create(:id => 4404, :name => "ТГК-11", :slug => "tgkk")
Company.create(:id => 4405, :name => "ТГК-13", :slug => "tgkm")
Company.create(:id => 4406, :name => "ТГК-14", :slug => "tgkn")
Company.create(:id => 4407, :name => "Тульская сбытовая компания", :slug => "tlsb")
Company.create(:id => 4408, :name => "Томская энергосбытовая компания", :slug => "tosb")
Company.create(:id => 4409, :name => "Ульяновскэнерго", :slug => "ulen")
Company.create(:id => 4410, :name => "Волгоградэнергосбыт", :slug => "vgsb")
Company.create(:id => 4411, :name => "Вологодская сбытовая компания", :slug => "vosb")
Company.create(:id => 4412, :name => "Якутскэнерго", :slug => "yaen")
Company.create(:id => 4413, :name => "Ярославская сбытовая компания", :slug => "yrsb")
Company.create(:id => 4414, :name => "Камгэсэнергострой", :slug => "kges")
Company.create(:id => 4415, :name => "Страховое общество Авиационный Фонд Единый Страховой (АФЕС)", :slug => "afes")
Company.create(:id => 4416, :name => "АК БАРС БАНК", :slug => "akbr")
Company.create(:id => 4417, :name => "АКИБАНК", :slug => "akib")
Company.create(:id => 4418, :name => "АльфаСтрахование", :slug => "alfs")
Company.create(:id => 4419, :name => "ОТП Банк", :slug => "bisi")
Company.create(:id => 4420, :name => "ЧЕЛИНДБАНК", :slug => "chlb")
Company.create(:id => 4421, :name => "Чрезвычайная страховая компания", :slug => "chsk")
Company.create(:id => 4422, :name => "СК Чувашия-Поддержка", :slug => "chvp")
Company.create(:id => 4423, :name => "Центр-инвест", :slug => "cinb")
Company.create(:id => 4424, :name => "ДальЖАСО", :slug => "dlgs")
Company.create(:id => 4425, :name => "САК ЭНЕРГОГАРАНТ", :slug => "engr")
Company.create(:id => 4426, :name => "Энергетическая Русская Компания", :slug => "erco")
Company.create(:id => 4427, :name => "ФФК", :slug => "ffco")
Company.create(:id => 4428, :name => "Финанс-Лизинг", :slug => "flko")
Company.create(:id => 4429, :name => "ФИНПРОМБАНК", :slug => "fpbn")
Company.create(:id => 4430, :name => "КБ Хлынов", :slug => "hlnb")
Company.create(:id => 4431, :name => "Ингосстрах", :slug => "ings")
Company.create(:id => 4432, :name => "КапиталЪ Страхование", :slug => "kaps")
Company.create(:id => 4433, :name => "Московский Банк Реконструкции и Развития", :slug => "mbrd")
Company.create(:id => 4434, :name => "Международный банк Санкт-Петербурга", :slug => "mbsp")
Company.create(:id => 4435, :name => "Банк Москвы", :slug => "mmbm")
Company.create(:id => 4436, :name => "Страховая компания Москва", :slug => "mosc")
Company.create(:id => 4437, :name => "Московская страховая компания", :slug => "mssk")
Company.create(:id => 4438, :name => "Петрокоммерц", :slug => "petr")
Company.create(:id => 4439, :name => "Росбанк", :slug => "rosb")
Company.create(:id => 4440, :name => "ОСАО Россия", :slug => "ross")
Company.create(:id => 4441, :name => "Фондовая биржа РТС", :slug => "rtsx")
Company.create(:id => 4442, :name => "Сбербанк", :slug => "sber")
Company.create(:id => 4443, :name => "СОГАЗ", :slug => "sogp")
Company.create(:id => 4444, :name => "Банк Санкт-Петербург", :slug => "stbk")
Company.create(:id => 4445, :name => "ТКБ", :slug => "tcbn")
Company.create(:id => 4446, :name => "Банк ВТБ", :slug => "vtbr")
Company.create(:id => 4447, :name => "Банк Возрождение", :slug => "vzrz")
Company.create(:id => 4448, :name => "НОМОС-БАНК", :slug => "nmos")
Company.create(:id => 4449, :name => "Инвесткафе", :slug => "investcafe")
Company.create(:id => 4450, :name => "Проектные инвестиции", :slug => "prin")
Company.create(:id => 4451, :name => "АФК Система", :slug => "afks")
Company.create(:id => 4452, :name => "АРМАДА", :slug => "armd")
Company.create(:id => 4453, :name => "Башинформсвязь", :slug => "bisv")
Company.create(:id => 4454, :name => "КОМСТАР - Объединенные ТелеСистемы", :slug => "cmst")
Company.create(:id => 4455, :name => "Центральный телеграф", :slug => "cntl")
Company.create(:id => 4456, :name => "Дагсвязьинформ", :slug => "dagi")
Company.create(:id => 4457, :name => "Сибирьтелеком", :slug => "enco")
Company.create(:id => 4458, :name => "ЦентрТелеком", :slug => "esmo")
Company.create(:id => 4459, :name => "Дальсвязь", :slug => "espk")
Company.create(:id => 4460, :name => "ЮТК", :slug => "kubn")
Company.create(:id => 4461, :name => "МГТС", :slug => "mgts")
Company.create(:id => 4462, :name => "Морион", :slug => "mori")
Company.create(:id => 4463, :name => "МТС", :slug => "mtss")
Company.create(:id => 4464, :name => "ВолгаТелеком", :slug => "nnsi")
Company.create(:id => 4465, :name => "О2ТВ", :slug => "odtv")
Company.create(:id => 4466, :name => "Ростелеком", :slug => "rtkm")
Company.create(:id => 4467, :name => "Северо-Западный Телеком", :slug => "sptl")
Company.create(:id => 4468, :name => "Таттелеком", :slug => "ttlk")
Company.create(:id => 4469, :name => "Уралсвязьинформ", :slug => "ursi")
Company.create(:id => 4470, :name => "Вымпелком", :slug => "vimp")
Company.create(:id => 4471, :name => "Apple", :slug => "aapl")
Company.create(:id => 4472, :name => "Ютинет", :slug => "yutinet")
Company.create(:id => 4473, :name => "РНТ", :slug => "rnav")
Company.create(:id => 4474, :name => "Аэрофлот", :slug => "aflt")
Company.create(:id => 4475, :name => "Омский аэропорт", :slug => "arpo")
Company.create(:id => 4476, :name => "Амурское пароходство", :slug => "asco")
Company.create(:id => 4477, :name => "Аэропорт Толмачево", :slug => "atlm")
Company.create(:id => 4478, :name => "В/О Авиаэкспорт", :slug => "aves")
Company.create(:id => 4479, :name => "Красэйр", :slug => "avka")
Company.create(:id => 4480, :name => "Территориальное агентство воздушных сообщений Кубань", :slug => "avsk")
Company.create(:id => 4481, :name => "Енисейское речное пароходство", :slug => "erpa")
Company.create(:id => 4482, :name => "ДВМП (FESCO)", :slug => "fesh")
Company.create(:id => 4483, :name => "Международный аэропорт Краснодар", :slug => "makr")
Company.create(:id => 4484, :name => "Международный аэропорт Курумоч", :slug => "maku")
Company.create(:id => 4485, :name => "Мурманский морской торговый порт", :slug => "mscp")
Company.create(:id => 4486, :name => "Ванинский морской торговый порт", :slug => "mtpv")
Company.create(:id => 4487, :name => "Мурманское морское пароходство", :slug => "mush")
Company.create(:id => 4488, :name => "Мурманский траловый флот", :slug => "mutf")
Company.create(:id => 4489, :name => "НМТП", :slug => "nmtp")
Company.create(:id => 4490, :name => "Новороссийское морское пароходство", :slug => "nompp")
Company.create(:id => 4491, :name => "Приморское морское пароходство", :slug => "prim")
Company.create(:id => 4492, :name => "Авиакомпания Ютэйр", :slug => "tmat")
Company.create(:id => 4493, :name => "Трансаэро", :slug => "trns")
Company.create(:id => 4494, :name => "РЖД", :slug => "rzhd")
Company.create(:id => 4495, :name => "ТрансКонтейнер", :slug => "trcn")
Company.create(:id => 4496, :name => "Алтайкрайгазсервис", :slug => "akgs")
Company.create(:id => 4497, :name => "Аганнефтегазгеология", :slug => "angg")
Company.create(:id => 4498, :name => "Арктикнефтегазстрой", :slug => "angs")
Company.create(:id => 4499, :name => "Астраханьоблгаз", :slug => "asog")
Company.create(:id => 4500, :name => "Башнефть", :slug => "bane")
Company.create(:id => 4501, :name => "Башкирнефтепродукт", :slug => "banp")
Company.create(:id => 4502, :name => "Белозернефть", :slug => "beln")
Company.create(:id => 4503, :name => "Белгородоблгаз", :slug => "bogz")
Company.create(:id => 4504, :name => "Брянскоблгаз", :slug => "brog")
Company.create(:id => 4505, :name => "НПО Буровая техника", :slug => "buth")
Company.create(:id => 4506, :name => "Центрэнергогаз - Газпром", :slug => "cegz")
Company.create(:id => 4507, :name => "Черногорнефть", :slug => "chgz")
Company.create(:id => 4508, :name => "Читаоблгаз", :slug => "chog")
Company.create(:id => 4509, :name => "Газпром", :slug => "gazp")
Company.create(:id => 4510, :name => "Гипровостокнефть", :slug => "gpvn")
Company.create(:id => 4511, :name => "Гипроспецгаз", :slug => "gsgz")
Company.create(:id => 4512, :name => "Газ-Сервис Республики Башкортостан", :slug => "gsrb")
Company.create(:id => 4513, :name => "Газавтоматика - Газпром", :slug => "gzav")
Company.create(:id => 4514, :name => "Хабаровскнефтепродукт", :slug => "hanf")
Company.create(:id => 4515, :name => "Интегра-Геофизика", :slug => "ingf")
Company.create(:id => 4516, :name => "Ивановооблгаз", :slug => "ivog")
Company.create(:id => 4517, :name => "Комигаз", :slug => "kgaz")
Company.create(:id => 4518, :name => "Карелгаз", :slug => "klgz")
Company.create(:id => 4519, :name => "Калугаоблгаз", :slug => "klog")
Company.create(:id => 4520, :name => "Костромаоблгаз", :slug => "koog")
Company.create(:id => 4521, :name => "Курскгаз", :slug => "krgz")
Company.create(:id => 4522, :name => "Красноярскнефтепродукт", :slug => "krnf")
Company.create(:id => 4523, :name => "Кировоблгаз", :slug => "krog")
Company.create(:id => 4524, :name => "Курганоблгаз", :slug => "kuog")
Company.create(:id => 4525, :name => "Ленгазспецстрой", :slug => "legs")
Company.create(:id => 4526, :name => "Леноблгаз", :slug => "leog")
Company.create(:id => 4527, :name => "ЛУКОЙЛ", :slug => "lkoh")
Company.create(:id => 4528, :name => "Липецкоблгаз", :slug => "lpog")
Company.create(:id => 4529, :name => "Славнефть-Мегионнефтегаз", :slug => "mfgs")
Company.create(:id => 4530, :name => "Моснефтепродукт", :slug => "mnef")
Company.create(:id => 4624, :name => "Полиметалл", :slug => "pmtl")
Company.create(:id => 4531, :name => "Роснефть-Мурманскнефтепродукт", :slug => "mynt")
Company.create(:id => 4532, :name => "Нефтемаркет", :slug => "nfmt")
Company.create(:id => 4533, :name => "Новые Горизонты", :slug => "ngor")
Company.create(:id => 4534, :name => "Научно-исследовательский и проектный институт по переработке газа", :slug => "nipg")
Company.create(:id => 4535, :name => "Нижегородоблгаз", :slug => "nnog")
Company.create(:id => 4536, :name => "НОВАТЭК", :slug => "nvtk")
Company.create(:id => 4537, :name => "Омскоблгаз", :slug => "omog")
Company.create(:id => 4538, :name => "Оренбургоблгаз", :slug => "orog")
Company.create(:id => 4539, :name => "Роснефть", :slug => "rosn")
Company.create(:id => 4540, :name => "Ростовоблгаз", :slug => "rtbg")
Company.create(:id => 4541, :name => "Рязаньоблгаз", :slug => "rzog")
Company.create(:id => 4542, :name => "Саратовнефтепродукт", :slug => "sarn")
Company.create(:id => 4543, :name => "Газпром нефть", :slug => "sibn")
Company.create(:id => 4544, :name => "Смоленскоблгаз", :slug => "smog")
Company.create(:id => 4545, :name => "Сургутнефтегаз", :slug => "sngs")
Company.create(:id => 4546, :name => "Татнефть", :slug => "tatn")
Company.create(:id => 4547, :name => "ТНК-BP Холдинг", :slug => "tnbp")
Company.create(:id => 4548, :name => "Транснефть", :slug => "trnfp")
Company.create(:id => 4549, :name => "Ярославльоблгаз", :slug => "yrog")
Company.create(:id => 4550, :name => "НК Альянс", :slug => "alnc")
Company.create(:id => 4551, :name => "Акрон", :slug => "akrn")
Company.create(:id => 4552, :name => "НК Роснефть-Алтайнефтепродукт", :slug => "alnp")
Company.create(:id => 4553, :name => "Аммофос", :slug => "ammo")
Company.create(:id => 4554, :name => "Апатит", :slug => "apat")
Company.create(:id => 4555, :name => "Азот", :slug => "azkm")
Company.create(:id => 4556, :name => "Биохимик", :slug => "bioh")
Company.create(:id => 4557, :name => "Березниковский содовый завод", :slug => "brsz")
Company.create(:id => 4558, :name => "Балаковорезинотехника", :slug => "brtk")
Company.create(:id => 4559, :name => "Череповецкий Азот", :slug => "chea")
Company.create(:id => 4560, :name => "Дорогобуж", :slug => "dgbz")
Company.create(:id => 4561, :name => "ЕЗСК", :slug => "efzk")
Company.create(:id => 4562, :name => "Галоген", :slug => "galo")
Company.create(:id => 4563, :name => "Химпром", :slug => "himc")
Company.create(:id => 4564, :name => "ИСКОЖ", :slug => "iskz")
Company.create(:id => 4565, :name => "Славнефть-ЯНОС", :slug => "jnos")
Company.create(:id => 4566, :name => "КуйбышевАзот", :slug => "kazt")
Company.create(:id => 4567, :name => "ШК Амтел-Поволжье", :slug => "kirt")
Company.create(:id => 4568, :name => "Саратовский НПЗ", :slug => "krkn")
Company.create(:id => 4569, :name => "Куйбышевнефтеоргсинтез", :slug => "kuos")
Company.create(:id => 4570, :name => "Казаньоргсинтез", :slug => "kzos")
Company.create(:id => 4571, :name => "Машиностроительный завод", :slug => "masz")
Company.create(:id => 4572, :name => "Метафракс", :slug => "mefr")
Company.create(:id => 4573, :name => "Мелеузовские минудобрения", :slug => "memy")
Company.create(:id => 4574, :name => "Метан", :slug => "metn")
Company.create(:id => 4575, :name => "Московский НПЗ", :slug => "mnpz")
Company.create(:id => 4576, :name => "Нефтемаслозавод", :slug => "nefz")
Company.create(:id => 4577, :name => "Нижнекамскнефтехим", :slug => "nknc")
Company.create(:id => 4578, :name => "Нижнекамскшина", :slug => "nksh")
Company.create(:id => 4579, :name => "Омский каучук", :slug => "omka")
Company.create(:id => 4580, :name => "Омскшина", :slug => "omsh")
Company.create(:id => 4581, :name => "Приаргунское производственное горно-химическое объединение", :slug => "pghop")
Company.create(:id => 4582, :name => "Сильвинит", :slug => "silv")
Company.create(:id => 4583, :name => "Сода, г. Стерлитамак", :slug => "sodd")
Company.create(:id => 4584, :name => "Уфанефтехим", :slug => "ufncp")
Company.create(:id => 4585, :name => "Уфимский НПЗ", :slug => "unpz")
Company.create(:id => 4586, :name => "Уралкалий", :slug => "urka")
Company.create(:id => 4587, :name => "Химпром", :slug => "vhim")
Company.create(:id => 4588, :name => "Алданзолото", :slug => "aldz")
Company.create(:id => 4589, :name => "АЛРОСА-Нюрба", :slug => "alnu")
Company.create(:id => 4590, :name => "Ашинский металлургический завод", :slug => "amez")
Company.create(:id => 4591, :name => "Армагус", :slug => "armg")
Company.create(:id => 4592, :name => "Альметьевский трубный завод", :slug => "atza")
Company.create(:id => 4593, :name => "Бурятзолото", :slug => "brzl")
Company.create(:id => 4594, :name => "ЧТПЗ", :slug => "chep")
Company.create(:id => 4595, :name => "ЧКПЗ", :slug => "chkz")
Company.create(:id => 4596, :name => "Северсталь", :slug => "chmf")
Company.create(:id => 4597, :name => "Челябинский металлургический комбинат", :slug => "chmk")
Company.create(:id => 4598, :name => "Чусовской металлургический завод", :slug => "chmz")
Company.create(:id => 4599, :name => "Челябинский цинковый завод", :slug => "chzn")
Company.create(:id => 4600, :name => "Коммунаровский рудник", :slug => "cryd")
Company.create(:id => 4601, :name => "Дмитровский опытный завод алюминиевой и комбинированной ленты", :slug => "dzkl")
Company.create(:id => 4602, :name => "Электроцинк", :slug => "eltz")
Company.create(:id => 4603, :name => "ЕЗ ОЦМ", :slug => "ezcm")
Company.create(:id => 4604, :name => "Гайский ГОК", :slug => "ggok")
Company.create(:id => 4605, :name => "Норникель", :slug => "gmkn")
Company.create(:id => 4606, :name => "Химико-металлургический завод", :slug => "hmtz")
Company.create(:id => 4607, :name => "Ижсталь", :slug => "igst")
Company.create(:id => 4608, :name => "Икар", :slug => "ikar")
Company.create(:id => 4609, :name => "ПАО Инкар", :slug => "inka")
Company.create(:id => 4610, :name => "Косогорский металлургический завод", :slug => "kmtz")
Company.create(:id => 4611, :name => "Кокс", :slug => "koks")
Company.create(:id => 4612, :name => "Каменск-Уральский металлургический завод", :slug => "kymz")
Company.create(:id => 4613, :name => "Ключевский завод ферросплавов", :slug => "kzff")
Company.create(:id => 4614, :name => "Кировский завод по обработке цветных металлов", :slug => "kzom")
Company.create(:id => 4615, :name => "Кировградский завод твердых сплавов", :slug => "kzts")
Company.create(:id => 4616, :name => "Лензолото", :slug => "lnzl")
Company.create(:id => 4617, :name => "Лысьвенский металлургический завод", :slug => "lsmz")
Company.create(:id => 4618, :name => "ММК", :slug => "magn")
Company.create(:id => 4619, :name => "Металлургический завод им. А.К. Серова", :slug => "metz")
Company.create(:id => 4620, :name => "Соликамский магниевый завод", :slug => "mgnz")
Company.create(:id => 4621, :name => "Мечел", :slug => "mtlr")
Company.create(:id => 4622, :name => "НЛМК", :slug => "nlmk")
Company.create(:id => 4623, :name => "Полюс Золото", :slug => "plzl")
Company.create(:id => 4625, :name => "Синарский трубный завод", :slug => "sntz")
Company.create(:id => 4626, :name => "Северский трубный завод", :slug => "svtz")
Company.create(:id => 4627, :name => "Тагмет", :slug => "tamz")
Company.create(:id => 4628, :name => "ТМК", :slug => "trmk")
Company.create(:id => 4629, :name => "Уралэлектромедь", :slug => "uelm")
Company.create(:id => 4630, :name => "Комбинат Южуралникель", :slug => "unkl")
Company.create(:id => 4631, :name => "ВСПМО-Ависма", :slug => "vsmo")
Company.create(:id => 4632, :name => "Белгородасбестоцемент", :slug => "belc")
Company.create(:id => 4633, :name => "Бамтоннельстрой", :slug => "btst")
Company.create(:id => 4634, :name => "Центродорстрой", :slug => "cdst")
Company.create(:id => 4635, :name => "ЧЕЛЖБИ-1", :slug => "chzb")
Company.create(:id => 4636, :name => "СИТИ", :slug => "city")
Company.create(:id => 4637, :name => "Дальмостострой", :slug => "dmoa")
Company.create(:id => 4638, :name => "Дорисс", :slug => "dors")
Company.create(:id => 4639, :name => "ДСК-3", :slug => "dskc")
Company.create(:id => 4640, :name => "ДСК-1", :slug => "dskt")
Company.create(:id => 4641, :name => "Гипросвязь", :slug => "gips")
Company.create(:id => 4642, :name => "Горнозаводскцемент", :slug => "gzce")
Company.create(:id => 4643, :name => "Искитимцемент", :slug => "iskc")
Company.create(:id => 4644, :name => "КМАпроектжилстрой", :slug => "kmap")
Company.create(:id => 4645, :name => "Костромской силикатный завод", :slug => "ksiz")
Company.create(:id => 4646, :name => "Трансстрой", :slug => "ktrs")
Company.create(:id => 4647, :name => "Лато", :slug => "lato")
Company.create(:id => 4648, :name => "Лесосибирский ЛДК №1", :slug => "lldk")
Company.create(:id => 4649, :name => "Лентелефонстрой", :slug => "ltst")
Company.create(:id => 4650, :name => "Мордовцемент", :slug => "mdcm")
Company.create(:id => 4651, :name => "Мосинжстрой", :slug => "mist")
Company.create(:id => 4652, :name => "Моспромстройматериалы", :slug => "mpsm")
Company.create(:id => 4653, :name => "Мостотрест", :slug => "mstt")
Company.create(:id => 4654, :name => "Мостожелезобетонконструкция", :slug => "mzbk")
Company.create(:id => 4655, :name => "НЕКК", :slug => "nekk")
Company.create(:id => 4656, :name => "ПИК", :slug => "pikk")
Company.create(:id => 4657, :name => "Группа ЛСР", :slug => "lsrg")
Company.create(:id => 4658, :name => "Группа РТМ", :slug => "rtmc")
Company.create(:id => 4659, :name => "Белон", :slug => "blng")
Company.create(:id => 4660, :name => "Кузбассразрезуголь", :slug => "kzru")
Company.create(:id => 4661, :name => "Распадская", :slug => "rasp")
Company.create(:id => 4662, :name => "КТК", :slug => "kbtk")
Company.create(:id => 4663, :name => "Архангельский ЦБК", :slug => "acbk")
Company.create(:id => 4664, :name => "Аскольд", :slug => "asko")
Company.create(:id => 4665, :name => "Юрьев-Польская ткацко-отделочная фабрика Авангард", :slug => "avng")
Company.create(:id => 4666, :name => "Завод железобетонных изделий Бетфор", :slug => "betf")
Company.create(:id => 4667, :name => "Боровичский комбинат огнеупоров", :slug => "bkog")
Company.create(:id => 4668, :name => "Богдановичское ОАО Огнеупоры", :slug => "bogn")
Company.create(:id => 4669, :name => "Борский стекольный завод", :slug => "borg")
Company.create(:id => 4670, :name => "Сокольский ЦБК", :slug => "ccbk")
Company.create(:id => 4671, :name => "Домнаремонт", :slug => "dmnr")
Company.create(:id => 4672, :name => "Фирма Энергозащита", :slug => "fenz")
Company.create(:id => 4673, :name => "Гостиница Советская", :slug => "gsov")
Company.create(:id => 4674, :name => "Институт прикладной физики", :slug => "iaph")
Company.create(:id => 4675, :name => "Институт Гипропрос", :slug => "igip")
Company.create(:id => 4676, :name => "Иркутсккабель", :slug => "ikbl")
Company.create(:id => 4677, :name => "Группа Илим", :slug => "ilim")
Company.create(:id => 4678, :name => "Капитал М", :slug => "kapm")
Company.create(:id => 4679, :name => "Карболит", :slug => "karb")
Company.create(:id => 4680, :name => "Кубаньвзрывпром", :slug => "kbvp")
Company.create(:id => 4681, :name => "Красноярскгеология", :slug => "kggk")
Company.create(:id => 4682, :name => "Кондопога", :slug => "kndo")
Company.create(:id => 4683, :name => "Коршуновский ГОК", :slug => "kogk")
Company.create(:id => 4684, :name => "Краснокамский завод металлических сеток", :slug => "kzms")
Company.create(:id => 4685, :name => "УК Ленинец", :slug => "lbit")
Company.create(:id => 4686, :name => "Ленэкспо", :slug => "lnep")
Company.create(:id => 4687, :name => "Лесозавод - 2", :slug => "lszc")
Company.create(:id => 4688, :name => "НИИ молекулярной электроники и завод Микрон", :slug => "mkro")
Company.create(:id => 4689, :name => "Междуречье", :slug => "mzdr")
Company.create(:id => 4690, :name => "Новокаолиновый ГОК", :slug => "ngok")
Company.create(:id => 4691, :name => "Новорослесэкспорт", :slug => "nole")
Company.create(:id => 4692, :name => "ЦМТ", :slug => "wtcm")
Company.create(:id => 4693, :name => "Брокерский дом Открытие", :slug => "open")
Company.create(:id => 4694, :name => "РАО ЭС Востока", :slug => "vrao")
Company.create(:id => 4695, :name => "ИСКЧ", :slug => "iskj")
Company.create(:id => 4696, :name => "Алроса", :slug => "alrs")
Company.create(:id => 4697, :name => "Фосагро", :slug => "phor")
Company.create(:id => 4698, :name => "РУСАЛ", :slug => "rualr")
Company.create(:id => 4699, :name => "Абрау – Дюрсо", :slug => "abrd")
Company.create(:id => 4700, :name => "FxPro", :slug => "fxpr")
