Feed.create(:id => 1, :name => "Rss_yandex", :url => "http://news.yandex.ru/business.rss", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 2, :name => "ManualRss", :url => "http://icfdev.ru", :source_id => "0", :type => "Source::Manual", :articles_count => "0")
Feed.create(:id => 3, :name => "ria news", :url => "http://ria.ru/export/rss2/economy/index.xml", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 4, :name => "vesti", :url => "http://www.vesti.ru/section.rss?cid=6", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 5, :name => "rusnews", :url => "http://www.rusnovosti.ru/rss/economics.xml", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 6, :name => "gazeta-ru", :url => "http://www.gazeta.ru/export/rss/financial.xml", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 7, :name => "newsru", :url => "http://feeds.newsru.com/com/www/section/finance", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 8, :name => "rambler", :url => "http://news.rambler.ru/rss/popular/economics/", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 9, :name => "vz", :url => "http://www.vz.ru/rss.xml", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 10, :name => "lenta business", :url => "http://lenta.ru/rss/news/business/", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 11, :name => "lenta finance", :url => "http://lenta.ru/rss/news/finance/", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 12, :name => "lenta economy", :url => "http://lenta.ru/rss/news/economy", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 13, :name => "mail economy", :url => "http://news.mail.ru/rss/economics/", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 14, :name => "investcafe", :url => "http://feeds.feedburner.com/skyline2", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 15, :name => "vestifinance", :url => "http://www.vestifinance.ru/yandex.xml", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 16, :name => "rbc", :url => "http://static.feed.rbc.ru/rbc/logical/rbcdaily.ru/daily.rss", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 17, :name => "forex", :url => "http://feeds.feedburner.com/profi-forex/PYBo", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 18, :name => "bfm", :url => "http://www.bfm.ru/news/rss/articles/", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 19, :name => "expert-all", :url => "http://expert.ru/doc-list/rss/", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 20, :name => "expert-bisness", :url => "http://expert.ru/doc-list/rss/?tags=3", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 21, :name => "indemedents gazeta", :url => "http://www.ng.ru/ng.rss", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 22, :name => "rg", :url => "http://www.rg.ru/xml/index.xm", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
Feed.create(:id => 23, :name => "fontanka", :url => "http://www.fontanka.ru/fontanka.rss", :source_id => 0, :type => "Feed::Rss", :articles_count => 0)
