#!/usr/bin/env ruby
require File.expand_path('../../config/application', __FILE__)
require 'forever'

Pythia::Application.load_tasks

Forever.run do
  before :each do
    Rake::Task['environment'].invoke
  end

  every 20.minute do
    Feed.all.map{ |f| f.collect_articles }
  end
end
